'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

	'''<summary>
	'''Form1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''lblTotalActividades control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTotalActividades As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblActividadesNoIniciadas control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblActividadesNoIniciadas As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblActividadesIniciadas control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblActividadesIniciadas As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblActividadesFinalizadas control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblActividadesFinalizadas As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''grdDatos control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdDatos As Global.System.Web.UI.WebControls.GridView
End Class
