'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Site

	'''<summary>
	'''HeadContent control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

	'''<summary>
	'''mnumaestros control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents mnumaestros As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''lblNombreUsuario control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblNombreUsuario As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''MainContent control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

	'''<summary>
	'''btnCerrarSesion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCerrarSesion As Global.System.Web.UI.HtmlControls.HtmlAnchor
End Class
