'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wfrmNuevaActividad

	'''<summary>
	'''lblTitulo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTitulo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''TxtFechaInicial control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TxtFechaInicial As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtFechaFinal control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFechaFinal As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cboPrioridad control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboPrioridad As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''cboTipoProgreso control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboTipoProgreso As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''cboUsuario control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboUsuario As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtActividad control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtActividad As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnGrabar control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnGrabar As Global.System.Web.UI.HtmlControls.HtmlAnchor
End Class
